name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Run the CI workflow when a PR is opened against `main`

jobs:
  test:
    runs-on: ubuntu-latest  # Run the workflow on an Ubuntu machine
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch the code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Use Python 3.10 (ensure compatibility)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies
          pip install pytest  # Ensure pytest is installed

      - name: Run tests
        run: pytest  # Run the test suite
# triggers upon a PR