name: CICD Pipeline

on:
  pull_request:
    branches:
      - main  # Run the workflow when a PR is opened against `main`

jobs:
  test:
    runs-on: ubuntu-latest  # Run the tests on Ubuntu
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch the code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Use Python 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest

      - name: Run tests
        run: pytest  # Run the test suite
        #should run upon a PR